[SETUP]
Databases=1
LogId=                                                                   
LogPass=
serverName=
token=

[Database1]
Database = AdventureWorks2012
filename = AdventureWorks2012.bak


[MAIL]
Server= 
Userid= 
Password=
email=
name=

[FTP]
Server=
Port=
Userid=
Password=
InitialDirectory=//
Pasive = Y 
Ascii = N

[OPTIONS]
ProgramMode=
Compress=
CompressFormat=
Ftp=
Ftp_FileMode=
SendMail= 
RestoreOrBackup=
CMD=





